# Generated by Django 5.1.1 on 2025-09-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
