# Generated by Django 5.1.1 on 2025-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='price',
        ),
        migrations.AddField(
            model_name='report',
            name='item_receipt',
            field=models.CharField(blank=True, default='No Receipt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='payment_status',
            field=models.CharField(blank=True, default='Paid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='unit',
            field=models.CharField(blank=True, default='Pcs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
